wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1719162066
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 23
      4: 3.12.3
      5: 0.17.1
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
